<a href="https://colab.research.google.com/github/Hoooooou-Jun/DEEEEEEPLearing_Colab/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# NumPy
# • Numerical Python : Python을 활용한 과학 컴퓨팅 전용 패키지
# • 복잡한 행렬계산, 선형대수, 통계 등을 Python에서 쉽게 다룰 수 있도록
# 도와줌
# • Python list로는 고성능 수치계산이 어렵기 때문에, Numpy의 array로 수치계산을 수행
# • 생성함수
# – array : 파이썬 리스트를 ndarray 형태로 변환
# – arrange : 파이썬 range 함수와 동일, ndarray 객체 생성 – zeros/ones/eye/full
# • 연산함수
# – add/subtract/multiply/divide : 사칙연산 – sum/prod : 원소의 합/곱
# – max/min : 최대/최소값 반환
# • 형상함수
# – shape/reshape/transpose
import numpy as np
np.__version__

'1.21.6'

In [6]:
# 배열
x = np.array([1.0, 2.0, 3.0])

print(x)

type(x)

[1. 2. 3.]


numpy.ndarray

In [7]:
# 산술 연산
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

x + y
x - y
x * y
x / y

x / 2.0

array([0.5, 1. , 1.5])

In [11]:
# 2차원 배열
a = np.array([[1, 2], [3, 4]])

print(a)

a.shape

b = np.array([[1, 2], [3, 4]])
a + b
a * b
a * 10

[[1 2]
 [3 4]]


array([[10, 20],
       [30, 40]])

In [12]:
# Broadcast
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

a * b

array([[10, 40],
       [30, 80]])

In [13]:
x = np.array([[51, 55],
              [14, 19],
              [0, 4]])

x[0]
x[0][1]

for row in x:
  print(row)

[51 55]
[14 19]
[0 4]
