<a href="https://colab.research.google.com/github/Hoooooou-Jun/DEEEEEEPLearing_Colab/blob/main/tensorflow_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
# 텐서플로 기본단위 및 함수 정리
import tensorflow as tf
import numpy as np
tf.__version__

'2.8.2'

In [55]:
hello = tf.constant("Hello TensorFlow")
print(hello.numpy())

b'Hello TensorFlow'


In [39]:
# Scalar
a = tf.constant(1)
b = tf.constant(2)

print(a)
tf.constant(1, shape=None, dtype=tf.int32)

print(tf.rank(a))

a = tf.cast(a, tf.float16)
print(a.dtype)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
<dtype: 'float16'>


In [18]:
tf.math.add(a, b)
tf.math.subtract(a, b)
tf.math.multiply(a, b)
tf.math.divide(a, b)
tf.math.mod(a, b)
tf.math.floordiv(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [22]:
# Vector
py_list = [10., 20., 30.]
num_arr = np.array([10., 10., 10.])

v1 = tf.constant(py_list, dtype=tf.float32)
v2 = tf.constant(num_arr, dtype=tf.float32)

tf.rank(v1)
tf.math.add(v1, v2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([20., 30., 40.], dtype=float32)>

In [27]:
tf.math.subtract(v1, v2)
tf.math.multiply(v1, v2)
tf.math.divide(v1, v2)
tf.math.mod(v1, v2)
tf.math.floordiv(v1, v2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [30]:
tf.reduce_sum(v1)
tf.math.square(v1)
tf.math.sqrt(v1)
print(v1 + 1)

tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)


In [32]:
# Matrix
list = [[10, 20],[30, 40]]
m1 = tf.constant(list)
tf.rank(m1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [40]:
v1 = tf.constant([1, 0])
v2 = tf.constant([-1, 2])
m2 = tf.stack([v1, v2])
tf.rank(m2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [43]:
e_mul = tf.math.multiply(m1, m2)
print(e_mul)
tf.rank(e_mul)

e_bc = tf.math.multiply(m1, 3)
print(e_bc)
tf.rank(e_bc)

tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [46]:
# Matrix 연산
mat_mul = tf.matmul(m1, m2)
print(mat_mul)
tf.rank(mat_mul)

a1 = tf.math.add(m1, m2)
a2 = m1 + m2

tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)


In [50]:
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


In [53]:
# 고차원 Tensor
m1 = [[1,2,3,4],[5,6,7,8]]
m2 = [[9,10,11,12],[13,14,15,16]]
m3 = [[17,18,19,20],[21,22,23,24]]

t1 = tf.constant([m1,m2,m3])

t2 = tf.stack([m1,m2,m3])

In [57]:
v1 = [1,2,3,4]
v2 = [5,6,7,8]
v3 = [9,10,11,12]
v4 = [13,14,15,16]
v5 = [17,18,19,20]
v6 = [21,22,23,24]

arr = [[v1,v2],
       [v3,v4],
       [v5,v6]]
       
t3 = tf.constant(arr)
t4 = tf.stack([t1,t2])

In [62]:
# Indexing, Slicing
vec = tf.constant([10,20,30,40,50])
vec[0]
vec[-1]
vec[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [69]:
mat = tf.constant([[10, 20, 30], [40, 50, 60]])
mat[0, 2]
mat[0, :]
mat[:, 1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 50], dtype=int32)>

In [77]:
nums = list(range(5))

print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8, 9]
print(nums)

TypeError: ignored

In [81]:
b = np.array([[1, 2, 3, 4], [5, 6,7, 8], [9, 10, 11, 12]])

print(b.ndim)
print(b.shape)
print(b[:,-1])
print(b[-1])
print(b[-1,:])
print(b[-1,...])
print(b[0:2,:])

2
(3, 4)
[ 4  8 12]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


In [89]:
a = np.array([1,2,3,4,5])

a[1:3]
a[-1]
a[0:2] = 9

In [90]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9,10,11,12]])

b[:,1]
b[-1]
b[-1,:]
b[-1,...]
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
# Reshape (형태 변환)
ts = tf.constant(range(0,24))
print(ts)
ts1 = tf.reshape(ts,[3,8])
print(ts1)

t2 = tf.reshape(t1,[-1,4])
t3 = tf.reshape(t2,[-1])
t4 = tf.reshape(t3,[-1,3,4])
t5 = tf.reshape(t4,[3,2,4])
t6 = tf.reshape(t5,[3,2,2,2])
print(t6)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)
tf.Tensor(
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]], shape=(3, 2, 2, 2), dtype=int32)


In [98]:
a = np.arange(12)
a.reshape(3,4)
a.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [100]:
# 변수 (잘 안씀)
t1 = tf.constant([[0,1,2],
                  [3,4,5]])
tv1 = tf.Variable(t1)
print(tv1)
tv1.assign([[1,1,1],
            [2,2,2]])
t2 = tf.convert_to_tensor(tv1)
tv2 = tf.Variable(t2, name='name')

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>
